http:
  routers:
    test:
      rule: Host(`test.preview.morawskim.pl`)
      service: test
  services:
    test:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
