http:
  routers:
    test:
      rule: Host(`test.preview.morawskim.pl`)
      service: test
      entryPoints:
        - web
    ttrss:
      rule: Host(`ttrss.morawskim.pl`)
      service: ttrss
      tls:
        certResolver: myresolver
    nextcloud:
      rule: Host(`nextcloud.morawskim.pl`)
      service: nextcloud
      tls:
        certResolver: myresolver
    test2:
      rule: Host(`test.morawskim.pl`)
      service: test2
    testInternal:
      rule: Host(`test.docker`)
      service: testInternal
    ots:
      rule: Host(`ots.morawskim.pl`)
      service: ots
      tls:
        certResolver: myresolver
    jsonplaceholder:
      rule: Host(`jsonplaceholder.morawskim.pl`)
      service: jsonplaceholder
      tls:
        certResolver: myresolver
    webpage2kindle:
      rule: Host(`kindle.morawskim.pl`)
      service: webpage2kindle
      tls:
        certResolver: myresolver
    webmail:
      rule: Host(`webmail.morawskim.pl`)
      service: webmail
      tls:
        certResolver: myresolver
  services:
    test:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    ttrss:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:32080
    nextcloud:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:32080
    test2:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    testInternal:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    ots:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:32080
    jsonplaceholder:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:32080
    webpage2kindle:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:32080
    webmail:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:32080
