http:
  routers:
    test:
      rule: Host(`test.preview.morawskim.pl`)
      service: test
      entryPoints:
        - web
    test2:
      rule: Host(`test.morawskim.pl`)
      service: test2
    testInternal:
      rule: Host(`test.docker`)
      service: testInternal
    tapo:
      rule: Host(`tapo.docker`)
      service: tapo
      entryPoints:
        - internal
    ots:
      rule: Host(`ots.morawskim.pl`)
      service: ots
      tls:
        certResolver: myresolver
    jsonplaceholder:
      rule: Host(`jsonplaceholder.morawskim.pl`)
      service: jsonplaceholder
      tls:
        certResolver: myresolver
    webpage2kindle:
      rule: Host(`kindle.morawskim.pl`)
      service: webpage2kindle
      tls:
        certResolver: myresolver
  services:
    test:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    test2:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    testInternal:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    tapo:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    ots:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    jsonplaceholder:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
    webpage2kindle:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://k8s:80
