apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ots
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`ots.10.0.2.15.nip.io`)
      services:
        - kind: Service
          name: ots
          port: 80
      middlewares:
        - name: add-x-forwarded-proto
