- name: Install node_exporter
  package:
    name:
      - golang-github-prometheus-node_exporter
- name: Enable and start node_exporter
  service: name=prometheus-node_exporter state=started enabled=yes
- name: firewalld enable node_exporter
  firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
    zone: internal
- name: Configure node-exporter
  lineinfile:
    path: /etc/sysconfig/prometheus-node_exporter
    regexp: '^ARGS='
    line: ARGS=--web.listen-address=0.0.0.0:9100
  notify: Restart node_exporter
