ports:
  web:
    exposedPort: 80
    nodePort: 32080
  websecure:
    exposedPort: 443
    nodePort: 32443
  internal:
    port: 8081
    exposedPort: 81
    nodePort: 32081
    protocol: TCP
ingressClass:
  isDefaultClass: false
service:
  type: NodePort
logs:
  access:
    # -- To enable access logs
    enabled: true
