apiVersion: v1
kind: Service
metadata:
  name: resnet101-image-labels
spec:
  selector:
    app: resnet101-image-labels
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
