---
- hosts: docker
  become: true
  gather_facts: no
  vars:
    username: ubuntu

  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install docker
      package:
        name:
          - docker.io
          - docker-compose
    - name: Start docker
      service: name=docker enabled=true state=started
    - name: Add docker to the user's groups
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
    - name: Create a docker's network
      docker_network:
        name: traefik 
    - name: Deploy traefik via docker-compose
      docker_compose:
        project_name: traefik
        definition:
          version: '3.3'
          services:
            traefik:
                image: traefik:1.7
                restart: unless-stopped
                ports:
                  - 80:80
                  - 443:443
                  - 8888:8080
                networks:
                  - traefik
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock
                  - acme:/acme
                command: 
                  - --configfile=/dev/null
                  - --api
                  - --docker
                  - --docker.watch
                  - --docker.network=traefik
                  - --docker.exposedbydefault=false
                  - --logLevel=INFO
                  # more specific  
                  - --debug=false
                  - --defaultentrypoints=https,http
                  - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
                  - --entryPoints=Name:https Address::443 TLS
                  - --retry
                  - --acme.email=marcin@morawskim.pl
                  - --acme.storage=/acme/acme.json
                  - --acme.entryPoint=https
                  - --acme.onHostRule=true
                  - --acme.httpchallenge.entrypoint=http
                  #- --acme.caServer="https://acme-staging-v02.api.letsencrypt.org/directory"
          networks:
            traefik:
                external: true
          volumes:
            acme:
