timezone: 'Europe/Warsaw'
user_default_shell: '/bin/bash'
users:
  marcin:
    home: '/home/marcin'
    purge_ssh_keys: true
    gid: 'marcin'
    groups: [adm, cdrom, sudo, dip, plugdev, lxd]

ssh_keys:
  'marcin.morawski@sensilabs.pl':
    type: 'ssh-rsa'
    key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDZDsJ38k7nRmVqGLUIpctPHW+Keo4v6eF3MFqVzgRImaspB+hfI/2zP5PjMiTxtVSkMOPSrii2hgSdFA5wElrK5JW7XFNWdNvky/d/Df0VBCADO5I7fRg3kfUDOG+GGLCzYZvfLyZ+EsveJ0Q65Pe24W51lZ28I48LedYEjXfgZ0yoDDCa8MEQH58Id1QZKFi/sR+bgHBqug3zARO/fQIebkmD3BCssahGzxOpWo8n1FrRDxw0vcF9urghm+P4aemDBPf+NOCJguDjwFaWhxQzAK/AMNo8CaEY+rMabFLMwGXUw1TPWXl48i71UzCk/Gdd9KW+aY4g7Pk4pTHLJkw9'
  'tomasz.zalewski@sensilabs.pl':
    type: 'ssh-rsa'
    key: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQCyz3ChgS366mN3PubRSxilVFhdlnvKG0zfOGTpDSNZHOrnLtjc6edJDZy7uvPT0HfocvWkzlpiQBJqm+2Yh7oeLSlvSK+LfukYWlBGwwk7YEwj0sN0Qce5XMO6OdHIRTCOmHijfF+CZo0JfLccryUEc1RowNwkXxcLQmPHAMCDEUeMOyxOJ3i9zk/oc1+IONFLZ11RLdi5KqW6B3ehpRp/vVhKG+YCnQsluS/M1vAGJ7/wZhmDTW4XjfkvCy7AOw1QWFK+q3eecU/KtnJ89npD41a4TYmWGH0oyFA4REkoVRZ40tPe6zSvAScJHriEt0vErtq8bZ9KFBD5NCX9hmVyIcyWJZd5RcBRWVJEAzAvfDAQq0X8XWyCwinDtyK3a/bFfmQ+f5VOIN2qyR36KxS45fOBkD9CvptI7/qWFc2KO/aAxlScqkSO3zey7Fhb7DUfbGrAHMG1Aa6F+qhaV/Lc04Ijuzlq1akSKbTCqLi+It6EjSzre3dySxmi7grVmRxEfdxA3kuG9IIolmZE4XIA6sI+qd7nFWHqehqunRiX2MR1/ectHJ99DOGYPdxfO9tXHEhZck+ugqVmbHEXgxFUjYcQOfLMi5tgBl/FN3CXyk+CjAptfM3LP/UFwvsXpu9+tpSDIE3aUubyW4WnORZs0MbbIjjFv80621v7vO3jiw=='
  'ssorder-deploy':
    type: 'ssh-rsa'
    key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDWkGjR/hTbWe9Ik7/3IEFt5KCNx9VSGgI7GIMXSYZKHJ+Js1c2h5rWN2+/MoYu703CgkYGL9YRTGqd7M9/m4yCuaTAqdmVfS2OtnvaPh8NMPTW+r5hmxZhH1Sg8cArt4QMZy/yIGiLIvPKpAog7i7HyjhxmzAGbdVenSSmlu0odJ9ZljFIDKZwJ2vz7/kdMnnhYjYgIrdCbCNpdlF7GiA4ShKdABmVaYsNzBGLnXj4lL130Tl0Mkk0xBLzBywbdE1MolnjwbIemJVooFYFgWHO8vCPHAuxIXK2OgK8Dcmc5tmgswCJ2sXth9MHOZ4OQcQlqbS5w86xT6fpuTloSLBt'

sensi::provision_repo::repo_url: 'https://github.com/morawskim/provision-dev-servers.git'
