---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: price-tracker
  namespace: prod
spec:
  encryptedData:
    CONFIG_URL: AgBmW0lOqVNvpDBlIRaCM5G4ZT52tuT1PyTOODT3MC873HwC5H7EUuJUsMBD0xFILJyU8H+6TGtYat89Pi2fhWPo9feyInlc76TgR+fqX/5woMz8EWbKF533TY7lALdXFiluJWU/We8rp/PMT0296QXfLfpG2KrBKsFwW1mx9yfuECsxukZDErM2uMmMpmEec22kF1yM8lPFI2zZP+OrjqQLPcvaQJjz9J3RAn8EDYVWWYbgwKvj+mN2gYHtpc8+M7LQDURatsCFLQE/aGl7LehGfbsTFDLl0olNeKE2P+iYflYXYxEapsgHfNrtlaaVogtiHGkDQyQnwnM42iliO7uQQPWsRHdevO/fGhbbpCKCJjgABuPMRS4y8WHY8Se4RmM/XBpsxDzDGGGqLdAo4iVOT2blbw/OM6d49FkKzRKFhprc83+0i8wIoOSyF+023iorfbBU9R/kqOHw/Huv581LySlxApxh3v0ath4rruO+BT39J3phUbrBihX4v0IcU8otFMK/BOJimAqLf7nkNeOtvUhigdMsq17xLzuk3m4Tq1/UhjtdNEXM7Bxaq6KPpyLy/CTPguTpW2GtVCqAp0ftpOhjhHR/phIVbZHuwsw1JsAD9Z0ZRtd8wZtdKBgO2/+qWa4Cx1wzG+vdWGQs3QQ/pdF8zM7jR3Ftyo4Ookj4pFFlNCZMb+vd7uhz7v6oeHilipQRYjdGcZAa7mOYPSKJkI5DBxXY3QV1D6CO4ebMiI+N6b8qbMNk8lu2fJmK7FTkIJCK/gU=
  template:
    metadata:
      creationTimestamp: null
      name: price-tracker
      namespace: prod
    type: Opaque