---
- name: Generate new root password
  command: openssl rand -base64 30 creates=/root/.my.cnf
  register: mysql_new_root_pass

# required python mysql package eg. MySQL-python
- name: MySQL remove anonymous users
  mysql_user: name="" host_all=true state=absent
  #when: mysql_new_root_pass.changed

- name: MySQL remove root remote host
  mysql_user: name="root" host="{{ ansible_fqdn }}" state=absent

- name: Remove test MySQL database
  mysql_db: name=test state=absent
  #when: mysql_new_root_pass.changed

- name: Update MySQL root password
  mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_new_root_pass.changed

- name: Create my.cnf
  template: src=my.cnf dest=/root/.my.cnf mode=0600
  when: mysql_new_root_pass.changed

- debug: msg="New root password is {{mysql_new_root_pass.stdout}}"
  when: mysql_new_root_pass.changed

- debug: msg="No change to root password"
  when: not mysql_new_root_pass.changed
