- name: Create env file for noip
  no_log: true
  template:
    src: templates/env.j2
    dest: "~/noip.env"
- name: Deploy noip via docker-compose
  docker_compose:
    project_name: noip
    definition:
      version: '3.3'
      services:
        app:
          image: morawskim/noip-client
          restart: "no"
          command: "noip:update -f /.env"
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
          volumes:
            - ~/noip.env:/.env:ro
        ofelia:
          image: mcuadros/ofelia:latest
          command: daemon --docker
          labels:
            ofelia.enabled: "true"
            ofelia.job-run.noip.schedule: "@every 5m"
            ofelia.job-run.noip.container: "noip_app_1"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
