---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: maddy
  namespace: prod
spec:
  encryptedData:
    MADDY_CLOUDFLARE_TOKEN: AgChyytrMWeAFzee3Zg17XpqnLIe+ZIrEJkJQcPaPxJmpRLwGpmHPS9oXR2TEHjnsz+b9XFG9w2nP7SEEOKcGiModF6pvgyhqc7QX4Hh55b2AUca7BGmYN0njIVHNVxHVrT7Ras+q4EKKpCxeane8Ssf3q6fdk+IkyH4jvDvyvcNe/4gN9H53vmOH0T2G2jn7rVsp1r34kfBDf+TAhEoLJ791GsR1kZBh56bSKoemyta/r0Oin1nssktlzdjRU6DfcPlL2oCEus270dJrJt4nX4QXX15cYGnl3A2vE8u3czxQjYMxSoPAoqhbuDuK4zxLya1p+fwBAFVuPXHuupbVa1FEa21Fjj+LEi7MnE/mHCTgzrWxjZm29nlmoW4HUnsyNTo/GFqnlWdj60OX+qj+1IJSAM1r5kOzNfbVHtvceqMjfqPo5q8q5z2OVIUQr+JylMy95VOy6nH13VOD/wK8+Jkid68eGDOyUGc9ZlqVMmxmL1BLf+u7pqZLkQN/jH3EqySTO6QWSNTpy4oHPGDwJYxmoCvq4R+ohutKJlC4y4GJ4uThPpzcRFEwnTR1Wob8BTdWEy9KOPxafQgoafZThaEQAcwsATDQv8Pm+V6UHTK8lrribdnNOykIM1k/9v5IT9OhforZSvqhcDHN9cMxT5/roX8zAI9pEcfb11eCDBkgK2mwBK08XH4Alhiu8uoXtqh/mCvjIPrsjHQxVkFouThjmfZVpW3BGb1CQqw5S5kcG4pRYlpx52g
  template:
    metadata:
      creationTimestamp: null
      name: maddy
      namespace: prod
    type: Opaque