# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2019-09-25 09:41:43 +0200 by marcin:
gem "puppet-lint", "~> 2.3"
