#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
mod 'puppetlabs-apt'
mod 'puppetlabs-docker', '3.7.0'
mod 'reidmv-yamlfile', '0.2.0'
mod 'puppetlabs-vcsrepo', '3.0.0'
mod 'puppet-systemd',
  :git => "git://github.com/camptocamp/puppet-systemd.git",
  :ref => '2.6.0'
mod 'puppet-archive', '4.2.0'
mod 'puppet-rpmkey',
  :git => "git://github.com/stschulte/puppet-rpmkey.git",
  :ref => 'v1.0.3'
mod 'puppet-zypprepo',
  :git => "git://github.com/deadpoint/puppet-zypprepo.git",
  :ref => 'v2.2.1'
mod 'puppet-firewalld', '4.1.1'

# A module from git
# mod 'puppetlabs-ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
