---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ddns-updater
spec:
  encryptedData:
    config.json: AgA11gf0izBpdlSdWZ6wDJYVJOsE6IRw7MpX4N7UGNzD053Gt+JHaelK2bxU7JAI6Sf9VLNHwykeT8MjK49I7hGn601wLj9pSN6IsLtFiS5ZmO5QbI7IWxB5zX5VduiVK9rH09t6OUtUcerC1evUhZATWJh9FH7n+tndMF0eIJA12Dc3jfB/kUp6LUU1ne4YsN7UewaxItb+m6E5VgZfqpNlcjszjm26aVqmKI6jac2UbnUNgXu8F73Tg4jCm/rDGeb651/fs0+Az615Sb0z/+oRVglZ7RQvLMp5LSt2J61jo3eIUAPa9qG4KMltr/WQbCiu0XDkHdx9xYuATF7j08OvGx7EsCRiZvm2Y3HwISg3qRDt/shoYxQXapNw3m1VKo1If0kbfSxymZ1uJAAp+zKPy1PLS0nkCaH2htJN9s3Djj5RR5APM5BFtmYd5EZ1FBkmySw6DwRA6ouAGqhzYtM3Z9wRIII9CnpHePXKW/G/DsCNi7ecM6c80abdY0TTyWL3PLV/5rDRpX+ACHrEi8Uyxu/S1hfRZY/qS7TUL+vcJ6rl4km5NnJOqldPg9PNWnNSvBZ+VUqy32Bn529j6CU/aHkS3ERjqVt8qqfWLKh0juPsuJmOV9T4fIpL4OQ1bGs4YMcJ8Ed08zcfrBpyIUZe4/xQ2Lkjxyh9KXuD4Q+PjsGM42ZomH6hSoWOFqI8MX05q3UMJ9wktiUNYGtuRLRnB280ugesxy7Jca75b0l+i5E8bJ1t7aZiDz7nWVTnpKfA1BypAVvIUMcRGNDvt18D5KKjsJLc0ZCboI3ccDqLi385/0AoscECcBaKTWC6OVw6AOIBQezHcGFCICNvv/70gD0odtHHTvNlZcddIo8YiP19gTVdb60PeIl9U7PTVjohRHIKxu2l3e7O87s3FgWIaPn+ZsE5WidLIMtuQUyQJdl8hBh50rduJFRStI7jRPKv+cKysK37zQji8v/48M73Rt2/eCDv75hZSqeJN6D2c4t7IqQAg1zgfCQD/MQsaKsCR3MToyPENY5jjr5rh061LIte+eJkIVRGVoIdaXbrxI/L1mNuIIZyQQc1QN9ok6ZvJI4=
  template:
    metadata:
      name: ddns-updater
