---
- hosts: localhost
  vars_files:
    - parameters/secretsK8s.yml
  tasks:
    - name: Create sealed secrets
      include_tasks: tasks/secrets.yml
      loop:
      - template: templates/openid.yml.j2
        dest: k8s/overlay/traefik/openid-auth-forward-sealed-secret.yml
      - template: templates/ddns-updater.yml.j2
        dest: k8s/overlay/prod/ddns-updater/sealed-secret.yml
      - template: templates/gitlab.yml.j2
        dest: k8s/overlay/prod/gitlab-ci-pipelines-exporter/sealed-secret.yml
      - template: templates/maddy.yml.j2
        dest: k8s/overlay/prod/maddy/sealed-secret.yml
      - template: templates/nextcloud.yml.j2
        dest: k8s/overlay/prod/nextcloud/sealed-secret.yml
      - template: templates/noip.yml.j2
        dest: k8s/overlay/prod/noip/sealed-secret.yml
      - template: templates/tapo.yml.j2
        dest: k8s/overlay/prod/tapo/sealed-secret.yml
      - template: templates/ttrss.yml.j2
        dest: k8s/overlay/prod/ttrss/sealed-secret.yml
      - template: templates/webpage2kindle.yml.j2
        dest: k8s/overlay/prod/webpage2kindle/sealed-secret.yml
      - template: templates/price-tracker.yml.j2
        dest: k8s/overlay/prod/price-tracker/config-sealed-secret.yml
      - template: templates/pipeline-games.yml.j2
        dest: k8s/overlay/pipeline/games/sealed-secret.yml
      - template: templates/matomo.yml.j2
        dest: k8s/overlay/prod/matomo/sealed-secret.yml
      - template: templates/games.yml.j2
        dest: k8s/overlay/prod/games/sealed-secret.yml
      - template: templates/mysqld-exporter.yml.j2
        dest: k8s/overlay/monitoring/mysqldExporterSealedSecret.yml
