apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy: {}
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus
      - name: config
        configMap:
          name: prometheus
          items:
            - key: config.yml
              path: prometheus.yml
      containers:
      - image: prom/prometheus:v2.36.2
        name: prometheus
        resources:
          requests:
            memory: 32Mi
          limits:
            memory: 128Mi
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus2
          - name: config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: "prometheus.yml"
status: {}
