apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy: {}
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus
      - name: config
        configMap:
          name: prometheus
          items:
            - key: config.yml
              path: prometheus.yml
            - key: node_export_alerts
              path: node_exporter.yml
      - name: secrets
        secret:
          secretName: prometheus
      containers:
      - image: prom/prometheus:v2.55.1
        name: prometheus
        resources:
          requests:
            memory: 32Mi
          limits:
            memory: 256Mi
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus
          - name: config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: "prometheus.yml"
          - name: config
            mountPath: /etc/prometheus/node_exporter.yml
            subPath: "node_exporter.yml"
          - name: secrets
            mountPath: /secrets
            readOnly: true
        ports:
        - containerPort: 9090
status: {}
