---
- hosts: localhost
  become: false
  connection: local
  tasks:
    - name: Git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
      with_items:
        - { repo: 'git@github.com:morawskim/vimdot.git', dest: '/home/marcin/.config/vim', version: 'master' }
        - { repo: 'https://github.com/Bash-it/bash-it.git', dest: '/home/marcin/.local/share/bash-it', version: 'fe78da73cc04f68420b5aed9faf431c9740db72f' }
        - { repo: 'https://github.com/tmux-plugins/tpm.git', dest: '/home/marcin/.tmux/plugins/tpm', version: 'master' }
        - { repo: 'https://github.com/facebook/PathPicker.git', dest: '/home/marcin/.local/share/PathPicker', version: '0.9.2' }
        - { repo: 'git@github.com:morawskim/provision-dev-servers.git', dest: '/home/marcin/projekty/provision-dev-servers', version: 'master' }
        - { repo: 'git@github.com:morawskim/morawskim.github.io.git', dest: '/home/marcin/projekty/morawskim.github.io', version: 'master' }
        - { repo: 'git@github.com:morawskim/rpm-pipeline.git', dest: '/home/marcin/projekty/rpm-pipeline', version: 'master' }
        - { repo: 'git@github.com:stasiu20/ssorder.git', dest: '/home/marcin/projekty/ssorder', version: 'develop' }

    - name: "Add additional remote repositories to ssorder"
      git_config:
        scope: local
        state: present
        repo: "/home/marcin/projekty/ssorder"
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      with_items:
        - { name: 'remote.private.url', value: 'git@gitlab.com:morawskim/private-ssorder.git' }
        - { name: 'remote.gitlab.url', value: 'git@gitlab.com:morawskim/ssorder.git' }

    - name: PathPicker symlink
      file:
        src: /home/marcin/.local/share/PathPicker/fpp
        dest: /home/marcin/.local/bin/fpp
        owner: marcin
        state: link

    - name: vimrc
      file:
        src: /home/marcin/.config/vim/vimrc
        dest: /home/marcin/.vimrc
        owner: marcin
        state: link
    - name: gvim
      file:
        src: /home/marcin/.config/vim/vimrc
        dest: /home/marcin/.gvimrc
        owner: marcin
        state: link
    - name: vim
      file:
        src: /home/marcin/.config/vim/
        dest: /home/marcin/.vim
        owner: marcin
        state: link
