- name: Parse template of secret {{item.template}}
  set_fact:
    template_output: "{{ lookup('template', item.template) }}"
# - name: Debug template content
#   debug:
#     msg: "template: {{ template_output }}"
- name: Encrypt secret resource
  command: kubeseal --controller-namespace kube-system --controller-name sealed-secrets-controller --format yaml
  args:
    stdin: "{{ template_output }}"
  register: sealed_secret
# - name: Debug sealed_secret
#   debug:
#     msg: "SealedSecret: {{ sealed_secret.stdout }}"
- name: Store SealedSecret in file {{item.dest}}
  copy:
    content: "{{ sealed_secret.stdout }}"
    dest: "{{item.dest}}"
