---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-ci-pipelines-exporter
spec:
  encryptedData:
    GCPE_GITLAB_TOKEN: AgBkGJ2X61IboV6sxZVi9EsduxJiJKiTAsextZv/1OrpAMII9tsvNfJIFMeuHnUB7RVmXqDhVxx46DT37CUGjz5sRP2ZagrXqUAtL5pmyR3QKiGGSJH8eb8e7b074P9DQSB4k/qQ6AIOeBOctNlJYyfiKXCzrU2viLudny5VzcsI+D6aErdEMCma78FEL55MaDm7BmTtsOUmvdgcmcAAY4NJytxe+RprPWULe1ebJKURzIi0IwdYqSQ2Jd0Ce5xyPMRNtGCaxqsJkyBbF4w5ZDJI2CdLLxHuRAkSolqvuc1NJE+GGJgY8GIOB9hCxqYv01pbhjfgSYVz8TPy6xy9BAO5jmeu61zxGip5xpX4HLE5M013QaQCfSHgS2fUG5KUdCOFcMd5DWpRfAS3KrKHB8laKPTwso3GkqJyRXzENY0IMrQg+2XtVOpp6AT9sQw6q4o6Cdn6ph/bWGWtgVLjGVhAELZcETROeYsxSasixPhsUbU/lFoVwX80Inzh4dpk2LmlNvIEg5WaPqdUbmGwXPhbpJXCw85gLl4U1/c6tCZizljEjjw4Y2vF0e9jrwqizPtfyh/bvl4fgGKrtlrkxb6h9pKkhvsgbmg3O5R993nywXnH7XTZ4c5dTHV6ziBjvVUj1RZKGW5uGYdESAG4zSn+ggMGCNchtbrnH7Lg7/QtS5nwdspIaHmW3yFzRC3RC6ERamSUh2hraVVgQersi6TaWske2KehgwJvWA==
  template:
    metadata:
      name: gitlab-ci-pipelines-exporter
