- name: Create configuration file for up-to-date-exporter
  template:
    src: templates/config.yml
    dest: "~/up-to-date-exporter.yml"
- name: Deploy up-to-date-exporter via docker-compose
  docker_compose:
    project_name: up-to-date-exporter
    pull: yes
    definition:
      version: '3.3'
      services:
        up-to-date-exporter:
          image: registry.gitlab.com/morawskim/up-to-date-exporter:main
          restart: unless-stopped
          volumes:
            - ~/up-to-date-exporter.yml:/etc/up-to-date-exporter.yml
          command:
            - --config.file
            - /etc/up-to-date-exporter.yml
          networks:
            - prometheus_default
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
      networks:
        prometheus_default:
            external: true
