---
- hosts: wazuh
  become: true
  vars_files:
    - parameters/secrets.yml
  tasks:
    - name: Install node-exporter
      package:
        name: prometheus-node-exporter
    - name: Start node-exporter
      service: name=prometheus-node-exporter enabled=true state=started
    - name: Fetch wazuh install script
      get_url:
        url: https://packages.wazuh.com/4.11/wazuh-install.sh
        dest: /root/wazuh-install.sh
        mode: '0755'
    - name: Install wazuh
      command: /root/wazuh-install.sh --all-in-one
    - import_tasks: ../common/fluent-bit.yml
    - name: Configure fluentbit
      template:
        src: templates/fluent-bit-custom.conf.j2
        dest: "/etc/fluent-bit/custom.conf"
        backup: true
        mode: 0644
