{
 "title": "web2kindle",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "push_to_kindle_synchronous 302",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_execution_time_bucket{method=\"POST\", status_code=\"302\", route=\"push_to_kindle_synchronous\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "push_to_kindle_synchronous / requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_execution_time_count{route=\"push_to_kindle_synchronous\", method=\"POST\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "web_extension / time bucket",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(app_execution_time_bucket{route=\"web_extension\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Push to kindle sync 302 / time bucket",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(app_execution_time_bucket{route=\"push_to_kindle_synchronous\", method=\"POST\", status_code=\"302\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}