concurrent = 4
check_interval = 0
listen_address = ":9252"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Ubuntu20.04 nuc"
  limit = 1
  url = "https://gitlab.com/"
  token = "{{ gitlab_runner_shell.runner.token }}"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "docker nuc"
  url = "https://gitlab.com/"
  token = "{{ gitlab_runner_docker.runner.token }}"
  executor = "docker"
  limit = 4
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "edbizarro/gitlab-ci-pipeline-php:7.2"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
