---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 1Gi
