- name: Create configuration file for traefikv2 internal
  template:
    src: templates/static-file-configuration.yml
    dest: "~/traefik2-internal.yml"
- name: Deploy traefikv2 via docker-compose
  docker_compose:
    project_name: traefikv2_internal
    definition:
      version: '3.3'
      services:
        traefik:
            image: traefik:v2.8
            restart: unless-stopped
            ports:
              - 8890:8080
            labels:
              traefik.enable: "true"
              traefik.port: "80"
              traefik.backend: "traefikv2internal"
              traefik.docker.network: traefik
              traefik.frontend.rule: "HostRegexp: {subdomain:[a-z]+}.docker"
            networks:
              - default
              - traefik
            volumes:
              - ~/traefik2-internal.yml:/etc/traefik/services.yml
            logging:
              driver: "json-file"
              options:
                max-file: "2"
                max-size: "20m"
            command:
              - --api.insecure=true
              - --providers.file.filename=/etc/traefik/services.yml
              - --providers.file.watch=true
            extra_hosts:
              - "test.docker:192.168.111.88"
              - "tapo.docker:192.168.111.88"
      networks:
        traefik:
            external: true
