---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-exporter
  namespace: monitoring
spec:
  encryptedData:
    OPENAI_ORG_ID: AgAibalwQYioO+Y1T6/mPBassjN7oU0nVm3pXjSRp808sPLVyYHt1bipzibO3BorJv3pmUMJhjzDcL4j1YL84hB00wgyorffWYqqUdDCWlpi9ttAhCtlq/jSj0nA9pTbpkxkCimjrwYqJW1kBo5MjZ+Vog6xGW+39u8M3kRW3z5SLMCniJ1bCGya/hOx2Q51iApdYTF6F3bf1Wzsj02pFI+UE+Q5OlCsh+GRoF6u83oDgUQhr1ykc+d8xeFapElbjp3xK77sG7agyOMOjzwucEjn0FGrJ387KFHZ33fdJ93r4YQiexT001r3eRjDnKKylW6P8xEUHjyQypFWcjCImDAAbehjc/7znOBI9QjGD11uC5dBY5/e1+HLTIFQ6wCxWwwuZY9VcWd6WkbWzB1u6QWEVIHV5utO6QChe0L4t/BrvYFwcT0l9oiDrfXygQteuC1AipXun5+UFQrC3ycczM+WzG7uGuGjUf3nelyttZJxaFY1eqUqWqjZYRwptbHL4uK95VJ6xm5eRk9j87L1iQ0LTD3XAP9HLLV8BOJ0fHVxDzfLQ9+SZsQf+/27kZb6SG9etuNZbR8bcB9xNWL0bEHOJGU6c6gsJCezUmhxwFmLX5FveAZt+DkijmTDBTAIjvpU2ZjQB0/i1Vq1/b/pTOClJSawQkpIFhrWesCmEi/bzXp1TrsOMIAlBlqrP/fkkVLJI8XZkfUcoii+R5F+B7Wyf3zNT/FlhopN9A6S
    OPENAI_SECRET_KEY: AgAwrCkMnireUHIAhEPqe2XPHdHvdGqyppattyt+IqOds9wN9Ux30JgYwXOALzzEczs1fqXkJeaqyhDf4gJ8sv0LAjF5hfs5MjD4utVt7bRT0cacBkHC8dNXmIo8l/Ck886/RrjNeGE16osY3+3vSVo65uRygWnLEWy22yhQvcq00GPlgTiga203HD8CtOcVlTvUXVi77QTsD+aYR0D99dL497kO+ulaOpQeE/DVxXRFtKOZf8PG1Zsg1QBGhVeMRpzGGOSdVPYQN5izVypxSe2naLRxnVzdKL2Nzox05bruYBLPxzkqK6P8UMPYCHV1E6LvKLqv81p2fny8dxAkkYcvv2mNLHs9BH9fPXL9oeUJSt49+yuWNIt512+BvEpElkxAW1vFS+sOdGmcUfi0pPmy3A7LDUDQ9okeu+kmefds+deOSTtNR2YnudvcWPL83mda2BgQ7LGiK4RtizQpjjMxzAlDLwL2YVzglmde6FJypmmp06U3xavo5F4jBsaMpw/hUI5tmvhpuSESD91UlGtPqAbyPLeuyyItfPF8bNnjEkf5pO9gidsfN3RqcwksWyjipeebefExU2isJUc6pMD/4yFRr6QLTUpI7Y9MWCMYAQpUm1ELRretIxv6FwENclfWqTXTTEp83o2PWK8ihTJco7DkQ9yQRB9ewpAosE+jS4Fek83Z9sdsGkvtj6QN03EUxyWd4e4Fguy+rBxoZQxPq/2zqDkLuCjTNSBNjQYYf1pUmXhdQEGIrl0Q2Vg2S6BtXCvWBXSp5R7Q7rwyfXxEnsnEU8edqvcDjPUCYQI0p/QkETc/CSIDeIe6yOgbQRbk0qingYlcj1vlE4KtUyFgLoFq3Xv0k0e/GyAaedG1FvFDZQtA
  template:
    metadata:
      creationTimestamp: null
      name: openai-exporter
      namespace: monitoring
    type: Opaque