apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 500Mi
