# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "morawskim/Ubuntu-18.04-amd64-minimal"
  config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.nested = true
      libvirt.cpu_feature :name => 'vmx', :policy => 'require'
  end

  # Disable default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  config.vm.network "forwarded_port", guest: 9252, host: 9252
  config.vm.network "forwarded_port", guest: 9103, host: 9103

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     export DEBIAN_FRONTEND=noninteractive
     apt-get update -qq
     apt-get install -y puppet git make
     gem install librarian-puppet
     mkdir -p /provision
     git clone https://github.com/morawskim/provision-dev-servers.git /provision
     pushd /provision/puppet
     librarian-puppet install
     popd
     cd /provision
     #make provision MANIFEST=gitlab-runner
  SHELL
end
