gitlab-runner ansible_host=vm-gitlab ansible_port=22 ansible_user=ubuntu
k8s ansible_host=vm-k8s ansible_port=22 ansible_user=ubuntu
nuc ansible_host=intel-nuc ansible_port=22 ansible_user=root
wazuh ansible_host=vm-wazuh ansible_port=22 ansible_user=ubuntu
srv1 ansible_host=192.168.33.110 ansible_port=22 ansible_user=marcin
