---
- hosts: nuc
  become: true
  vars:
    libvirt_default_pool_name: default
    #ansible_python_interpreter: /usr/bin/python3.8
    libvirt_dns: "{{ '192.168.111.1' if 'guest' != ansible_facts.virtualization_role else '192.168.120.1' }}"
  tasks:
    - name: Install required packages CLI
      package:
        name:
          - patterns-server-kvm_server
          - patterns-server-kvm_tools
          - qemu-ui-spice-core
          #- python3-firewall
        state: present
    - name: Start libvirtd
      service: name=libvirtd state=started enabled=yes
    - name: Update account
      user:
        name: "marcin"
        groups: [libvirt, systemd-journal]
        state: present
    - name: firewalld add interface to internal zone
      firewalld:
        zone: internal
        interface: "{{ ansible_facts.default_ipv4.interface }}"
        permanent: true
        state: enabled
    - include_tasks: tasks/libvirt.yml
    - name: "Include cups"
      include_tasks: tasks/cups.yml
      when: "'guest' != ansible_facts.virtualization_role"
    - include_tasks: tasks/cockpit.yml
  handlers:
    - name: Restart libvirtd
      service:
        name: libvirtd
        state: restarted
    - name: Restart cups
      service:
        name: cups
        state: restarted
