apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: games
spec:
  entryPoints:
    - internal
  routes:
    - kind: Rule
      match: Host(`games.i.morawskim.pl`)
      services:
        - kind: Service
          name: games
          port: 80
      middlewares:
        - name: openid-auth
        - name: add-x-forwarded-proto
