- name: "srv1 - setup kvm"
  hosts: srv1
  gather_facts: true
  become: true
  vars:
    user: marcin
    nicName: enp3s0

  tasks:
    - name: Check connection
      ansible.builtin.ping:

    - name: Set LIBVIRT_DEFAULT_URI env
      ansible.builtin.lineinfile:
        path: /home/{{user}}/.bash_profile
        regexp: '^\s*export LIBVIRT_DEFAULT_URI='
        line: "export LIBVIRT_DEFAULT_URI=qemu:///system"

    # {{{ Setup KVM
    - name: Add OpenTofu repository
      ansible.builtin.yum_repository:
        name: opentofu
        description: opentofu
        baseurl: "https://packages.opentofu.org/opentofu/tofu/rpm_any/rpm_any/$basearch"
        gpgcheck: yes
        repo_gpgcheck: no
        gpgkey:
          - https://get.opentofu.org/opentofu.gpg
          - https://packages.opentofu.org/opentofu/tofu/gpgkey
        enabled: yes
        sslverify: yes
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt
        metadata_expire: 300
    - name: Install packages
      ansible.builtin.package:
        state: present
        name:
          - tofu
          - qemu-kvm
          - libvirt
          - virt-top
          - bash-completion
    - name: Enable and start libvirtd
      ansible.builtin.service:
        name: libvirtd
        enabled: yes
        state: started
    - name: Add {{ user }} to libvirt group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: libvirt
        append: yes
    # }}}

    # {{{ NetworkManager bridge
    - name: NetworkManager br0
      ansible.builtin.copy:
        dest: /etc/NetworkManager/system-connections/br0.nmconnection
        owner: root
        group: root
        mode: '0600'
        content: |
          [connection]
          id=br0
          uuid=cc37a187-4ed4-45b6-8d51-b975bb156ba1
          type=bridge
          interface-name=br0
          timestamp=1775306909
          autoconnect=true

          [ethernet]

          [bridge]
          stp=false

          [ipv4]
          address1=192.168.33.110/24
          dns=8.8.8.8;8.8.4.4;
          gateway=192.168.33.1
          method=auto

          [ipv6]
          addr-gen-mode=default
          method=auto

          [proxy]

    - name: NetworkManager bridge-slave-{{nicName}}
      ansible.builtin.copy:
        dest: /etc/NetworkManager/system-connections/bridge-slave-{{nicName}}.nmconnection
        owner: root
        group: root
        mode: '0600'
        content: |
          [connection]
          id=bridge-slave-{{nicName}}
          uuid=b5765c50-0ce7-4ac3-968a-cd8f994edc02
          type=ethernet
          controller=br0
          interface-name={{nicName}}
          port-type=bridge

          [ethernet]

          [bridge-port]
    - name: Disable autoconnect for {{nicName}}
      ansible.builtin.ini_file:
        path: /etc/NetworkManager/system-connections/{{nicName}}.nmconnection
        section: connection
        option: autoconnect
        value: "false"
        mode: '0600'
        # backup: yes
    # }}}

    # {{{ libvirt pool
    - name: Create directory for images and disks
      ansible.builtin.file:
        path: /var/lib/libvirt/storage
        state: directory
        owner: root
        group: root
        mode: "0711"
    - name: Define a new storage pool
      community.libvirt.virt_pool:
        command: define
        name: storage
        xml: |
          <pool type='dir'>
            <name>storage</name>
            <target>
              <path>/var/lib/libvirt/storage</path>
            </target>
          </pool>
    - name: Start a storage pool
      community.libvirt.virt_pool:
        state: active
        name: storage
    - name: Ensure that a storage pool will be started at boot
      community.libvirt.virt_pool:
        autostart: true
        name: storage
    # }}}

    # {{{ libvirt bridge network
    - name: Define a new bridge network
      community.libvirt.virt_net:
        command: define
        name: bridge
        autostart: true
        xml: |
          <network connections='1'>
            <name>bridge</name>
            <uuid>1720fec3-e0f5-4a83-b989-70d811ffdd9d</uuid>
            <forward mode='bridge'/>
            <bridge name='br0'/>
          </network>
    - name: Start a network
      community.libvirt.virt_net:
        state: active
        name: bridge
    - name: Ensure that a network will be started at boot
      community.libvirt.virt_net:
        name: bridge
        autostart: true
    # }}}
