---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install required packages CLI
      package:
        name:
          - terraform
          - git
          - make
          - wget
          - ansible
          - libvirt-client
          - avahi
          - nss-mdns
          - mkisofs
          - sshpass
        state: present
    - name: Start avahi-dnsconfd.service
      service: name=avahi-dnsconfd state=started enabled=yes
    - name: Update account
      user:
        name: "vagrant"
        groups: [systemd-journal]
        state: present
        append: yes
    - name: Install firewalld
      package:
        name:
          - firewalld
          - patterns-server-kvm_tools
      when: "ansible_facts.nodename == 'leap'"
    - name: Start firewalld
      service: name=firewalld state=started enabled=yes
      when: "ansible_facts.nodename == 'leap'"
    - name: firewalld enable ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      with_items:
       - 5353/udp
       - 53791/udp
      when: "ansible_facts.nodename == 'leap'"
    - name: Add vagrant user to group libvirt
      user:
        name: "vagrant"
        groups: [libvirt]
        state: present
        append: yes
      when: "ansible_facts.nodename == 'leap'"
    - name: Copy ssh key
      copy:
        src: files/id_rsa
        dest: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        group: vagrant
        mode: '0600'
    - name: Copy ssh public key
      copy:
        src: files/id_rsa.pub
        dest: /home/vagrant/.ssh/id_rsa.pub
        owner: vagrant
        group: vagrant
        mode: '0644'
