---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_EXPORTER_TOKEN: AgBjeSYLq8dfj88nehxd7p2/ZMs8mwaVk7XOXTtYLF5FWDda3xVaPiqoo3M27wJiaDThuU+jQRxfrZ5ljxjNVciI1SJw65MxFCKJH3vmIje8BJtEFHKt1XrDsq6vOsYIyo82LMB4US/kQA8yB5CbYYe+pGm8iU4Zg3e3vgW/ZiKFGJl3ygBXW1OC0MsPLiwP4okDkSfoMNfuKKjz0VWLHg7cwDgAMLZBw71vKWNLmNeYuYL4sCx47yEXumAEZKabsnEfw8sBkD7256xqMp7nojA4QK491CzvGW7oiOyN/tOnAM6n9wvCXMB2e2qKFp7TyUGK47epEQdp7rKfGjxGf9/GBlKuQf1o7b/kO1BkSoEZUzB+gNOZrBK4Tm6JdIFJ+OE1zUfHD3uHKZmKKmXLQF9s6XHtUfrLxpOA6IPTKeixDV902j69yvDaP5APsEP+qnGxPAR+4iqwb+/ovG5mk9KlHOI89lC33BYGG4y7aoaG1ZbHEytx+Iznlrv50q09zi7PBwimQB3iG05cqPJ0NyckD6/BoCUJJxe9bKoNsLkJT3Bkd3bDxAxizLB42ZQwAdk+XBq+hL42ZR4V018LKovDTCdekiOWyNLZWQT8LfxMmZWZs81D667qFAMNzz/v0kPmiuQevsoLAxnSfwblLCnvY/PbTWkkpxlOam07w9moNr7i4wzTRrqNb7L3dXm4WzPMYm5n9wv/kDYNrN/IftYYBWq/xV7Au46HjOCEEWs4AmfM7Pai9BgW4IyLgKiauQwZ1URQZ+Ik0qliCg6cWgiB
  template:
    metadata:
      name: nextcloud
