- name: Add fluent-bit repo
  ansible.builtin.deb822_repository:
    name: fluentbit
    types: [deb]
    uris: "https://packages.fluentbit.io/ubuntu/{{ ansible_distribution_release }}"
    signed_by: https://packages.fluentbit.io/fluentbit.key
    suites: "{{ ansible_distribution_release }}"
    components: [main]
    state: present
    enabled: true
- name: Install fluent-bit
  package:
    name: fluent-bit
    state: present
- name: Ensure fluent-bit custom config file exists
  copy:
    content: ""
    dest: /etc/fluent-bit/custom.conf
    force: false
    group: root
    owner: root
    mode: 0744
- name: Add a line to the fluent-bit configuration
  lineinfile:
    path: /etc/fluent-bit/fluent-bit.conf
    line: '@INCLUDE custom.conf'
# Note (?m) which turns on MULTILINE mode so ^ matches any line's beginning
- name: Comment OUTPUT section block
  replace:
    path: /etc/fluent-bit/fluent-bit.conf
    after: '(?m)^\[OUTPUT\]'
    #before: '(^\r?\n)|(^[^\s])'
    before: '^[^\s]'
    regexp: '^(.+)$'
    replace: '# \1'
    backup: true
- name: Comment OUTPUT section
  replace:
    path: /etc/fluent-bit/fluent-bit.conf
    regexp: '^\[OUTPUT\]'
    replace: '# [OUTPUT]'
- name: Start fluent-bit
  service: name=fluent-bit state=started enabled=yes
