namespace: prod

resources:
- tapo/sealed-secret.yml
- tapo/ingress.yml
- webpage2kindle/sealed-secret.yml
- noip/sealed-secret.yml
- ddns-updater/sealed-secret.yml
- ddns-updater/ingress.yml
- gitlab-ci-pipelines-exporter/sealed-secret.yml
- gitlab-ci-pipelines-exporter/ingress.yml
- maddy/sealed-secret.yml
- ttrss/sealed-secret.yml
- nextcloud/sealed-secret.yml
- up-to-date-exporter/ingress.yml
- price-tracker/config-sealed-secret.yml
- price-tracker/ingress.yml
- matomo/sealed-secret.yml
- matomo/cronJob.yml
- games/sealed-secret.yml
- games/ingress.yml
- changedetection/ingress.yml
- jupyter/ingress.yml
- demo-index/ingress.yml
- resnet101-image-labels/ingress.yml
- memos/ingress.yml
- ../../base/tapo-metrics
- ../../base/noip
- ../../base/ots
- ../../base/jsonplaceholder
- ../../base/webpage2kindle
- ../../base/up-to-date-exporter
- ../../base/ddns-updater
- ../../base/gitlab-ci-pipelines-exporter
- ../../base/maddy
- ../../base/ttrss
- ../../base/traefik-middlewares
- ../../base/nextcloud
- ../../base/price-tracker
- ../../base/matomo
- ../../base/games
- ../../base/changedetection
- ../../base/jupyter
- ../../base/demo-index
- ../../base/resnet101-image-labels
- ../../base/memos

configMapGenerator:
- literals:
  - MERCURE_URL=http://webpage2kindle/.well-known/mercure
  - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/data.db
  - NODE_MICROSERVICE_URL=http://webpage2kindle-node-microservice
  - GO_READABILITY_MICROSERVICE_URL=http://go-readability-api:8080
  name: webpage2kindle-php-config
- behavior: merge
  literals:
  - TTRSS_SELF_URL_PATH=https://ttrss.morawskim.pl
  name: ttrss

# images:
#    - name: registry.gitlab.com/morawskim/webpage2kindle/symfony-app
#      newTag: rabbitmq

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: test.preview.morawskim.pl
  target:
    kind: Ingress
    name: podinfo
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: test.docker
  target:
    kind: Ingress
    name: nginx
- patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`ots.morawskim.pl`)
  target:
    kind: IngressRoute
    name: ots
- patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`jsonplaceholder.morawskim.pl`)
  target:
    kind: IngressRoute
    name: jsonplaceholder
- patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`kindle.morawskim.pl`)
  target:
    kind: IngressRoute
    name: webpage2kindle
- patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`webmail.morawskim.pl`)
  target:
    kind: IngressRoute
    name: roundcube
- patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`ttrss.morawskim.pl`)
  target:
    kind: IngressRoute
    name: ttrss
- patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`nextcloud.morawskim.pl`)
  target:
    kind: IngressRoute
    name: nextcloud
- patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`matomo.morawskim.pl`)
  target:
    kind: IngressRoute
    name: matomo

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
