bases:
- ../../base/tapo-metrics
- ../../base/noip
- ../../base/ots
- ../../base/jsonplaceholder
- ../../base/webpage2kindle
- ../../base/up-to-date-exporter
- ../../base/ddns-updater
- ../../base/gitlab-ci-pipelines-exporter
- ../../base/maddy
- ../../base/ttrss

namespace: prod

resources:
- tapo/sealed-secret.yml
- webpage2kindle/sealed-secret.yml
- noip/sealed-secret.yml
- ddns-updater/sealed-secret.yml
- gitlab-ci-pipelines-exporter/sealed-secret.yml
- maddy/sealed-secret.yml
- ttrss/sealed-secret.yml
- ttrss/restic-sealed-secret.yml

configMapGenerator:
- name: webpage2kindle-php-config
  literals:
  - MERCURE_URL=http://webpage2kindle/.well-known/mercure
  - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/data.db
  - NODE_MICROSERVICE_URL=http://webpage2kindle-node-microservice
  - GO_READABILITY_MICROSERVICE_URL=http://go-readability-api:8080
- name: ttrss
  behavior: merge
  literals:
  - TTRSS_SELF_URL_PATH=https://ttrss.morawskim.pl

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: test.preview.morawskim.pl
    target:
      kind: Ingress
      name: podinfo
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: test.docker
    target:
      kind: Ingress
      name: nginx
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: tapo.docker
    target:
      kind: Ingress
      name: tapo-metrics
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ots.morawskim.pl
    target:
      kind: Ingress
      name: ots
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: jsonplaceholder.morawskim.pl
    target:
      kind: Ingress
      name: jsonplaceholder
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kindle.morawskim.pl
    target:
      kind: Ingress
      name: webpage2kindle
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: up-to-date-exporter.docker
    target:
      kind: Ingress
      name: up-to-date-exporter
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: gitlab-ci-pipelines-exporter.docker
    target:
      kind: Ingress
      name: gitlab-ci-pipelines-exporter
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: webmail.morawskim.pl
    target:
      kind: Ingress
      name: roundcube
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ttrss.morawskim.pl
    target:
      kind: Ingress
      name: ttrss
