bases:
- ../../base/podinfo
- ../../base/nginx
- ../../base/tapo-metrics
- ../../base/ots
- ../../base/jsonplaceholder
- ../../base/webpage2kindle

namespace: prod

resources:
- tapo/sealed-secret.yml
- webpage2kindle/sealed-secret.yml

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: test.preview.morawskim.pl
    target:
      kind: Ingress
      name: podinfo
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: test.docker
    target:
      kind: Ingress
      name: nginx
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: tapo.docker
    target:
      kind: Ingress
      name: tapo-metrics
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ots.morawskim.pl
    target:
      kind: Ingress
      name: ots
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: jsonplaceholder.morawskim.pl
    target:
      kind: Ingress
      name: jsonplaceholder
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kindle.morawskim.pl
    target:
      kind: Ingress
      name: webpage2kindle

