---
- name: Install node-exporter
  package:
    name: prometheus-node-exporter
- name: Start node-exporter
  service: name=prometheus-node-exporter enabled=true state=started
- name: Configure node_exporter ARGS
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-node-exporter
    regexp: '^\s*ARGS='
    line: 'ARGS="{{ node_exporter_args | join(" ") }}"'
    backup: true
  notify:
    - Restart prometheus-node-exporter
