---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: euro-office
  namespace: prod
spec:
  encryptedData:
    JWT_SECRET: AgCr8ah7Bds+HaNqJoz1vPgCDrsSiwL481BvBJayinOoDH4O/EO0mSPM0kBnXeWfX/YmzrXnGM9ydlW0wc4mD/iN2fsUUNJGbrQiXoP1PsprQRnCDDHmY0hdRufVjVm+pdITcy1j33oDoKiAKdmRnYWV6tiaCnWKtynEaLT1XxYfo/MZxZ+L4Sa/u90YD0C35USI63qj8Q5O/4ZisdUdy+B2LZoPNTR+Nk/unpQHzN0JeZqGzfkRzbXYYqu5gu0M1GE6aBJ1cZRQx4cUcgNqIPaKxAG/37zFcEa9ZYhV1Z14vl292J0IQ8f0pJZQ+cKwhasxbetBFg/wBN9jGx5BEGro+bpTbIstU7bPwc/x5EZzQ3V1MfGCa34p4bhwsSAYRydgT/IjasbZj6W1cPAzX/oLbRAmimdVYAoZfuRUrCXu0giZtm7yfVsxrALyUEvQ2wr7+B1J7eKqXm/ZUV3qgtn5VBhyxUC7gHbXJAY2MeswtlIN5asxFyKm+LOo0myQKsKQGbzxVk6zTw8QEH6mg+kjFU9yhJarRfqCG2z8zU54Mv2hMo5ql3BfiUFiS9KXG//DYBRAb/G8LwGZaUflQ2l3t3DsTee80NS9GISNsi6Zv67nzr+SctinfUswOe1yiSipVm7NVfkbxmYC7h6DnMnBPfBnSrJpQzFb1DKmvWZWvm++uKkR0qJKKKtG/bkd+1xHYSxCy0Pm6jMck47LLgmr/NSIng==
  template:
    metadata:
      creationTimestamp: null
      name: euro-office
      namespace: prod
    type: Opaque