---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: euro-office
  namespace: prod
spec:
  encryptedData:
    JWT_SECRET: AgCLVXOhSticWjM3DQgmMKnOc+B4Z3yoPC3dENqCntTKpFC8DNJYiv36SPZ8E303IhOQqr8aqg1toJQobs0p64WYFMJzpGRl2Fj+lZYmQ+dUKPpwsyFUsONg4ABQGnM1cpZPjYXPVBNX8FXaXCk833HEtM5KOaPSY8u0afSff9G8IvXgokrlxRSYJRJASAy9F87p7cndkXWWPU8WexfFrjDMLWe8Y6CgjhgYmnYN8jcgJLtObr90BYVbzxP1AgAAbiV4r/cWL0eM6iyYXNj8LoaRK6P+B/q9dy29xXOeACJE5QqfM/jShrPjb50wbEMVwWlgkQ0NtNSC30KTBfhJXpXhO6K53iU5MwOpIN89mIcKs5jwdep7fKyCjGYk2eqaVbc35i3O+KdcNH/CgvD/AZofXdZ/KujdXNQqv4U+a5V9DFZ9cCO0PWAR+E0Ohufj07J0gl7yShDuY/v3FsHS2BvRYXaUuj7DoEH9vcKsIAz6ef7kOfihvY/mr17oasL6UXaSb7M+h0JSH2EJmenHes2wtsMKnW64Ybc45t7aNRZVA42Z0eIVKO+5j0gIudFfXFQzx6gRSzeCN4wN6Za6cI/ZahafQme+UHRpg8+5yI3jQ1bo/9e36LsIoLY6Xgr2D/OqvFLQ5apNeIR6DK7peF24yfyeBervfi/3jWyPxwquZVvG6JCQEStMcvu9Kb/IVLNo6wTR7Q20GQ6Y5s7jxSw5MucV2LH1M2dCVNEDP9Sd37nDf7/Y5qdu
  template:
    metadata:
      creationTimestamp: null
      name: euro-office
      namespace: prod
    type: Opaque