- name: Install backup software
  package:
    name:
      - ruby
      - cron
      - restic
- name: Creates backups directory
  file:
    path: "{{ BACKUP_DIR }}"
    state: directory
    owner: root
    group: root
    mode: '0750'
- name: Copy script to dump mysql databases
  copy:
    src: backup/dump-mysql.rb
    dest: /usr/local/bin/dump-mysql.rb
    owner: root
    group: root
    mode: '0755'
- name: Copy script to dump nextcloud
  copy:
    src: backup/nextcloud-backup.sh.j2
    dest: /usr/local/bin/nextcloud-backup.sh
    owner: root
    group: root
    mode: '0755'
- name: Copy script to backup
  copy:
    src: backup/backup.sh.j2
    dest: /usr/local/bin/backup.sh
    owner: root
    group: root
    mode: '0755'
- name: Creates a cron job for backup
  cron:
    name: "daily backup"
    special_time: daily
    user: root
    job: "/usr/local/bin/backup.sh {{ BACKUP_DIR }}"
    cron_file: backup
# {{{ restic
- name: Copy AWS wrapper
  copy:
    src: backup/aws-assume-role.sh
    dest: /usr/local/bin/aws-assume-role.sh
    owner: root
    group: root
    mode: '0700'
- name: Create env file for restic
  no_log: true
  template:
    src: backup/restic.env.j2
    dest: "/etc/default/restic.env"
    owner: root
    group: root
    mode: '0640'
- name: Create service's systemd unit
  template:
    src: backup/restic.service.j2
    dest: "/etc/systemd/system/restic.service"
- name: Create timer's systemd unit
  template:
    src: backup/restic.timer.j2
    dest: "/etc/systemd/system/restic.timer"
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Enable a service unit for restic
  systemd:
    name: restic.service
    enabled: yes
    state: stopped
- name: Enable a timer unit for restic
  systemd:
    name: restic.timer
    state: started
    enabled: yes
# }}}
