- name: Deploy jsonplaceholder via docker-compose
  docker_compose:
    project_name: jsonplaceholder
    definition:
      version: '3.3'
      services:
        app:
          image: morawskim/jsonplaceholder
          restart: unless-stopped
          labels:
            traefik.enable: "true"
            traefik.port: "3000"
            traefik.backend: "jsonplaceholder"
            traefik.docker.network: traefik
            traefik.frontend.rule: "Host: jsonplaceholder{{ APP_DOMAIN_SUFFIX }}"
            traefik.http.routers.jsonplaceholder.rule: "Host(`jsonplaceholder{{ APP_DOMAIN_SUFFIX }}`)"
          networks:
            - default
            - traefik
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
      networks:
        traefik:
            external: true
