- name: Deploy ots via docker-compose
  docker_compose:
    project_name: ots
    definition:
      version: '3.3'
      services:
        app:
          image: luzifer/ots:v0.18.1
          restart: unless-stopped
          labels:
            traefik.enable: "true"
            traefik.port: "3000"
            traefik.backend: "ots"
            traefik.docker.network: traefik
            traefik.frontend.rule: "Host: ots{{ APP_DOMAIN_SUFFIX }}"
            traefik.http.routers.ots.rule: "Host(`ots{{ APP_DOMAIN_SUFFIX }}`)"
          networks:
            - default
            - traefik
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
      networks:
        traefik:
            external: true
