- name: Create env file for webpage2kindle
  no_log: true
  copy:
    content: "{{ WEBPAGE2KINDLE_ENV_LOCAL }}"
    dest: "~/webpage2kindle.env"
- name: Create env file for webpage2kindle node
  no_log: true
  copy:
    content: "{{ WEBPAGE2KINDLE_ENV_NODE_LOCAL }}"
    dest: "~/webpage2kindle-node.env"
- name: Deploy webpage2kindle via docker-compose
  docker_compose:
    project_name: webpage2kindle
    pull: yes
    definition:
      version: '3.3'
      services:
        caddy:
          image: morawskim/webpage2kindle-caddy
          restart: unless-stopped
          labels:
            traefik.enable: "true"
            traefik.port: "80"
            traefik.backend: "webpage2kindle"
            traefik.docker.network: traefik
            traefik.frontend.rule: "Host: kindle{{ APP_DOMAIN_SUFFIX }}"
          networks:
            - default
            - traefik
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
        php:
          image: morawskim/webpage2kindle
          restart: unless-stopped
          env_file:
            - "~/webpage2kindle.env"
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
        node:
          image: morawskim/webpage2kindle-node
          restart: unless-stopped
          volumes:
            - ~/webpage2kindle-node.env:/app/.env
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
      networks:
        traefik:
            external: true
