- name: Create env file for webpage2kindle
  no_log: true
  copy:
    content: "{{ WEBPAGE2KINDLE_ENV_LOCAL }}"
    dest: "~/webpage2kindle.env"
- name: Create env file for webpage2kindle node
  no_log: true
  copy:
    content: "{{ WEBPAGE2KINDLE_ENV_NODE_LOCAL }}"
    dest: "~/webpage2kindle-node.env"
- name: Deploy webpage2kindle via docker-compose
  docker_compose:
    project_name: webpage2kindle
    pull: yes
    definition:
      version: '3.3'
      services:
        php:
          image: registry.gitlab.com/morawskim/webpage2kindle/symfony-app:main
          restart: unless-stopped
          environment:
            SERVER_NAME: ":80"
          env_file:
            - "~/webpage2kindle.env"
          labels:
            traefik.enable: "true"
            traefik.port: "80"
            traefik.backend: "webpage2kindle"
            traefik.docker.network: traefik
            traefik.frontend.rule: "Host: kindle{{ APP_DOMAIN_SUFFIX }}"
            traefik.http.routers.kindle.rule: "Host(`kindle{{ APP_DOMAIN_SUFFIX }}`)"
            traefik.http.routers.kindle.tls.certresolver: myresolver
            traefik.http.routers.kindle.tls: "true"
            traefik.http.services.php-kindle.loadbalancer.server.port: "80"
          networks:
            - default
            - traefik
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
          volumes:
            - "{{ansible_env.HOME}}/webpage2kindle.db:/app/var/data.db"
        consumer:
          image: registry.gitlab.com/morawskim/webpage2kindle/symfony-app:main
          restart: unless-stopped
          env_file:
            - "~/webpage2kindle.env"
          command: [ "/app/bin/console", "rabbitmq:multiple-consumer", "-m", "10", "pipeline" ]
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
          volumes:
            - "{{ansible_env.HOME}}/webpage2kindle.db:/app/var/data.db"
        node:
          image: registry.gitlab.com/morawskim/webpage2kindle/node-microservice:main
          restart: unless-stopped
          volumes:
            - ~/webpage2kindle-node.env:/app/.env
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
        go-readability-api:
          image: registry.gitlab.com/morawskim/webpage2kindle/go-microservice:main
          restart: unless-stopped
          command:
            - --http
            - :8080
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
        redis:
          image: redis:7.0-alpine
          command: ["--maxmemory", "50mb", "--maxmemory-policy", "allkeys-lru"]
          restart: unless-stopped
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
      networks:
        traefik:
            external: true
