- name: Create maddy config
  template:
    src: templates/maddy.conf.j2
    dest: "~/maddy.conf"
- name: Deploy maddy via docker-compose
  docker_compose:
    project_name: maddy
    definition:
      version: '3.4'
      services:
        maddy:
          image: foxcpp/maddy:latest
          ports:
            - "1025:25"
            - "10143:143"
            - "10587:587"
            - "10993:993"
          volumes:
            - maddydata:/data
            - ~/maddy.conf:/data/maddy.conf
          environment:
            MADDY_HOSTNAME: mx1.mail.mdemo.ovh
            MADDY_DOMAIN: mail.mdemo.ovh
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
      volumes:
        maddydata:
