- name: Create maddy config
  template:
    src: templates/maddy.conf.j2
    dest: "~/maddy.conf"
- name: Deploy maddy via docker-compose
  docker_compose:
    project_name: maddy
    definition:
      version: '3.4'
      services:
        maddy:
          image: foxcpp/maddy:latest
          ports:
            - "1025:25"
            - "10143:143"
            - "10587:587"
            - "10993:993"
          networks:
            - prometheus_default
          volumes:
            - maddydata:/data
            - ~/maddy.conf:/data/maddy.conf
          environment:
            MADDY_HOSTNAME: mx1.mail.mdemo.ovh
            MADDY_DOMAIN: mail.mdemo.ovh
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
        roundcube:
          image: roundcube/roundcubemail:1.6.x-apache
          environment:
            ROUNDCUBEMAIL_DEFAULT_HOST: ssl://mx1.mail.mdemo.ovh
            ROUNDCUBEMAIL_DEFAULT_PORT: 993
            ROUNDCUBEMAIL_SMTP_SERVER: tls://mx1.mail.mdemo.ovh
            ROUNDCUBEMAIL_SMTP_PORT: 587
            ROUNDCUBEMAIL_DB_TYPE: sqlite
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
          labels:
            traefik.enable: "true"
            traefik.port: "80"
            traefik.backend: "roundcubemail"
            traefik.docker.network: traefik
            traefik.frontend.rule: "Host: webmail{{ APP_DOMAIN_SUFFIX }}"
          networks:
            - traefik
            - default
      volumes:
        maddydata:
      networks:
        prometheus_default:
            external: true
        traefik:
            external: true
