apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webpage2kindle
  name: webpage2kindle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage2kindle
  strategy: {}
  template:
    metadata:
      labels:
        app: webpage2kindle
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: webpage2kindle
      initContainers:
      - name: create-db
        image: registry.gitlab.com/morawskim/webpage2kindle/symfony-app:main
        command:
          - "/app/bin/console"
          - "broadway:event-store:create"
        envFrom:
        - configMapRef:
            name: webpage2kindle-php-config
        volumeMounts:
        - name: shared-data
          mountPath: /app/var/data
      containers:
      - image: registry.gitlab.com/morawskim/webpage2kindle/symfony-app:main
        name: webpage2kindle
        env:
        - name: SERVER_NAME
          value: ":80"
        envFrom:
        - secretRef:
            name: webpage2kindle-php
        - configMapRef:
            name: webpage2kindle-php-config
        volumeMounts:
        - name: shared-data
          mountPath: /app/var/data
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webpage2kindle-consumer
  name: webpage2kindle-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage2kindle-consumer
  strategy: {}
  template:
    metadata:
      labels:
        app: webpage2kindle-consumer
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: webpage2kindle
      initContainers:
      - name: create-db
        image: registry.gitlab.com/morawskim/webpage2kindle/symfony-app:main
        command:
          - "/app/bin/console"
          - "broadway:event-store:create"
        envFrom:
        - configMapRef:
            name: webpage2kindle-php-config
        volumeMounts:
        - name: shared-data
          mountPath: /app/var/data
      containers:
      - image: registry.gitlab.com/morawskim/webpage2kindle/symfony-app:main
        name: consumer
        command: [ "/app/bin/console", "rabbitmq:multiple-consumer", "-m", "10", "pipeline" ]
        envFrom:
        - secretRef:
            name: webpage2kindle-php
        - configMapRef:
            name: webpage2kindle-php-config
        volumeMounts:
        - name: shared-data
          mountPath: /app/var/data
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webpage2kindle-node
  name: webpage2kindle-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage2kindle-node
  strategy: {}
  template:
    metadata:
      labels:
        app: webpage2kindle-node
    spec:
      containers:
      - image: registry.gitlab.com/morawskim/webpage2kindle/node-microservice:main
        name: webpage2kindle
        envFrom:
        - secretRef:
            name: webpage2kindle-node
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webpage2kindle-go
  name: webpage2kindle-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage2kindle-go
  strategy: {}
  template:
    metadata:
      labels:
        app: webpage2kindle-go
    spec:
      containers:
      - image: registry.gitlab.com/morawskim/webpage2kindle/go-microservice:main
        name: webpage2kindle
        args:
          - --http
          - :8080
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webpage2kindle-redis
  name: webpage2kindle-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage2kindle-redis
  strategy: {}
  template:
    metadata:
      labels:
        app: webpage2kindle-redis
    spec:
      containers:
      - image: redis:7.0-alpine
        name: redis
        args: ["--maxmemory", "50mb", "--maxmemory-policy", "allkeys-lru"]
        resources: {}
