apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpage2kindle
spec:
  rules:
  - host: "kindle.10.0.2.15.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webpage2kindle
            port:
              number: 80
  ingressClassName: public
