apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webpage2kindle
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 50Mi
