bases:
- ../../base/podinfo

namespace: vagrant

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: podinfo-vagrant.10.0.2.15.nip.io
    target:
      kind: Ingress
      name: podinfo
