- name: Create config file for ddns-updater
  no_log: true
  template:
    src: templates/config.json.j2
    dest: "~/ddns-updater.json"
- name: Deploy ddns-updater via docker-compose
  docker_compose:
    project_name: ddns-updater
    pull: yes
    definition:
      version: '3.3'
      services:
        updater:
          image: ghcr.io/qdm12/ddns-updater
          restart: unless-stopped
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
          volumes:
            - ~/ddns-updater.json:/updater/data/config.json
