---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: games
  namespace: pipeline
spec:
  encryptedData:
    FILE_URL: AgAq0nMQA4QSThZdzhoEHaWT9ONon07T3pLPBjRmOZVeodtoqyiCODNNyuVcI3rwIVsCC9lRZPA2XtbmkcBS2/EcyVZgFTApJ8XI+QSI2Oh/O+kPOuhjNrVyOUak4aZmHmRs9n37cuSWxta5LKPip+vFU6+iC6aiaPePKi8fIa2kdrkqMnI19LmPmD1j6J8huf+h90xRQUL5wZ9l2Pt79GDEGQHyROfh8aOuZDHpgdkBrwtv2PODs6N7tQNtXS3bNN+RuXABeP+SdJVfsP3tex77QxGGqBce0qCvgOnEV15oFidlvoXGGFVn+kuEoFttZNfTDweAfxmetPnqIaE3+xMIpS92+25FCHMAv6quAtKUw4S2T3Mj5gB2D7soJ/Pv6wh4G00KFL3/FuJ+kcc4f+XqhMsGQe8xMWJ8SrP0z/RWmvZKe8R2yJ/Lttr2lvk4Ry1wfc/UhRMWjW6RTSejMoSD/VeFQQAfj6PLrXbwE3hQ5IhpM2s8Ick36dkuL3qISbXJT9Yq6SVgQ7hDDUhUo9Zip+SpDvYD38LXiOjJZhnad94ZpCiE680EgbfAUJg9jLvJQYjKXt/wxec97eBShtiyxqSQtiV+ou0xSHOnKLlMb3moCDhwTqhgeXjBaQW8BKDhoCVArxNed5lix6hHyvDxbJBZ811puPYv59XFp99Y0WAcshIuyPVMgU62HKvm0lHnAXeU3uV5sjW+WTmPQGRknvBmxWXSIcdRsKYeUWDXZsoA/ngQKG1FRFwG7YuYsBYasf+rGZEcK5Hg4fMT/R8pdoAO+pEjtdDuZBBFoSA=
    PASSPHRASE: AgBQn3YAVw/qeZdh4W0fsY4fvd/bVze/DijL18VRyRcssOXGS9pCAgZCbasYMiOsiVfJ8t3v3gV0L3GfQEvQRG5JASqadmtGaYqL5YoNiD01aSNsqepwn23Sy3E4SVUGYwxDp7BQl9wme0qQ1N/pO9+OFoSBdrBFnUNeEcmcnx3NTTiMjNlpxEvhkWYE+DWmLOGg/HX+YllujtHI+uvuAPQdNLFCj86grDCNT1/I4NlSoe3vnsTlGna02fH6i84Y29eSK+tylVanokJa6Mmj/4JAkYGQWtM9YuFKtF8L7tmAGERx3o0JlQJHHAybFJJl17SukKC71kZbyUNYMQDRNtNr6iFjEMeArWWV4wWB7FG5i0ZjqS2WGRORZ2C6SFXfGZZ45vPT6BSvnkUMUfosLWKq6I4jfKNATtYzgS+OcG6cwnHQHTSu+r0Z0d5ZPn+49bxL4QPyw0L9I8JE/9KvExGez//kChMSNCu7jeTdSjALOz9YldMZAhrBfRPwul7/IbBS5vEQxwW5c8JWW6ruvbkCrvgq0wu0Z53YlhlOfFyEK+usrIltRTHQAvgx00e7kq6rxEQ7TGMHpMGKWBtavX3wys1YHh389JXztATOaC3YN1R3V6tufR5jr/HgKCMuYaW92d/A+/djZvunw/QeLgUz+d/SQkaijEI/xsGeg28ptoQ9QMgKzYo0s6mq1ICFXLkRfTkAEkQSLaKjpeLoAQ==
  template:
    metadata:
      creationTimestamp: null
      name: games
      namespace: pipeline
    type: Opaque