---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install required packages CLI
      package:
        name:
          - terraform
          - git
          - make
          - wget
          - ansible
          - libvirt-client
          - avahi
          - nss-mdns
        state: present
    - name: Start avahi-dnsconfd.service
      service: name=avahi-dnsconfd state=started enabled=yes
    - name: Update account
      user:
        name: "vagrant"
        groups: [systemd-journal]
        state: present
