---
- hosts: localhost
  become: false
  connection: local
  tasks:
    - name: Git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
        accept_hostkey: yes
      with_items:
        - { repo: 'https://github.com/morawskim/vimdot.git', dest: '/home/marcin/.config/vim', version: 'master' }
        - { repo: 'https://github.com/morawskim/morawskim.github.io.git', dest: '/home/marcin/projekty/morawskim.github.io', version: 'master' }
        - { repo: 'https://github.com/Bash-it/bash-it.git', dest: '/home/marcin/.local/share/bash-it', version: 'master' }
        - { repo: 'https://github.com/tmux-plugins/tpm.git', dest: '/home/marcin/.tmux/plugins/tpm', version: 'master' }
        - { repo: 'https://github.com/facebook/PathPicker.git', dest: '/home/marcin/.local/share/PathPicker', version: '0.9.2' }
        - { repo: 'https://github.com/qewer33/Exquisite.git', dest: '/home/marcin/.local/share/Exquisite', version: 'ef1a10d' }

    - name: Create local bin dir
      file:
        path: /home/marcin/.local/bin
        state: directory
        mode: '0700'

    - name: "Change the pushurl of git repository"
      git_config:
        scope: local
        state: present
        repo: "{{ item.repo }}"
        name: "remote.origin.pushurl"
        value: "{{ item.value }}"
      with_items:
        - { repo: '/home/marcin/.config/vim', value: 'git@github.com:morawskim/vimdot.git' }
        - { repo: '/home/marcin/projekty/morawskim.github.io', value: 'git@github.com:morawskim/morawskim.github.io.git' }

    - name: PathPicker symlink
      file:
        src: /home/marcin/.local/share/PathPicker/fpp
        dest: /home/marcin/.local/bin/fpp
        owner: marcin
        state: link

    - name: vimrc
      file:
        src: /home/marcin/.config/vim/vimrc
        dest: /home/marcin/.vimrc
        owner: marcin
        state: link
    - name: gvim
      file:
        src: /home/marcin/.config/vim/vimrc
        dest: /home/marcin/.gvimrc
        owner: marcin
        state: link
    - name: vim
      file:
        src: /home/marcin/.config/vim/
        dest: /home/marcin/.vim
        owner: marcin
        state: link

    - name: Load bash-it
      lineinfile:
        path: /home/marcin/.bashrc
        regexp: '^test -f ~/.config/bash/boot.sh'
        line: test -f ~/.config/bash/boot.sh && source ~/.config/bash/boot.sh

    - name: Install Exquisite
      command: plasmapkg2 --type=kwinscript -i .
      args:
        chdir: /home/marcin/.local/share/Exquisite/package
