- name: Create fluentbit config
  template:
    src: templates/fluent-bit-config.conf.j2
    dest: "~/fluent-bit-config.conf"
- name: Create fluentbit config
  template:
    src: templates/parsers.conf.j2
    dest: "~/parsers.conf"
- name: Deploy fluentbit via docker-compose
  docker_compose:
    project_name: fluentbit
    definition:
      version: '3.3'
      services:
        fluentbit:
          image: morawskim/newrelic-fluent-bit-output:1.12.3
          command: '--config=/fluent-bit/etc/config.conf'
          restart: unless-stopped
          volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - ~/fluent-bit-config.conf:/fluent-bit/etc/config.conf
            - ~/parsers.conf:/fluent-bit/etc/parsers.conf
          environment:
            LICENSE_KEY: "{{ NEWRELIC_LICENSE_KEY }}"
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
