- name: Add underscore if sufix is not empty
  set_fact:
    sufixWithOptionalUnderscore: "{{ '_' + sufix if sufix | length > 0 else '' }}"
- name: "debug variable sufixWithOptionalUnderscore"
  debug:
    var: sufixWithOptionalUnderscore
- name: "Create configuration file for traefikv2{{sufix}}"
  template:
    src: "templates/static-file-configuration{{sufixWithOptionalUnderscore}}.yml"
    dest: "~/traefik2{{sufixWithOptionalUnderscore}}.yml"
- name: Deploy traefikv2 via docker-compose
  docker_compose:
    project_name: traefikv2{{sufixWithOptionalUnderscore}}
    definition:
      version: '3.3'
      services:
        traefik:
            image: traefik:v2.8
            restart: unless-stopped
            ports:
              - "{{port}}:8080"
            labels:
              traefik.enable: "true"
              traefik.port: "80"
              traefik.backend: "traefikv2{{sufix}}"
              traefik.docker.network: traefik
              traefik.frontend.rule: "HostRegexp: {{regex}}"
            networks:
              - default
              - traefik
            volumes:
              - "~/traefik2{{sufixWithOptionalUnderscore}}.yml:/etc/traefik/services.yml"
            logging:
              driver: "json-file"
              options:
                max-file: "2"
                max-size: "20m"
            command:
              - --api.insecure=true
              - --providers.file.filename=/etc/traefik/services.yml
              - --providers.file.watch=true
            extra_hosts:
              - "test.docker:192.168.111.88"
              - "tapo.docker:192.168.111.88"
      networks:
        traefik:
            external: true
