- name: Create a docker's network
  docker_network:
    name: traefik
- name: "Create configuration file for traefikv2"
  template:
    src: "templates/static-file-configuration.yml"
    dest: "~/traefik2.yml"
- name: Deploy traefikv2 via docker-compose
  docker_compose:
    project_name: traefikv2
    state: "present"
    definition:
      version: '3.3'
      services:
        traefik:
            image: traefik:v2.8
            restart: unless-stopped
            ports:
              - "8888:8080"
              - "80:80"
              - "81:81"
              - "443:443"
            labels:
              traefik.enable: "true"
              traefik.port: "80"
              traefik.backend: "traefikv2"
              traefik.docker.network: traefik
              traefik.frontend.rule: "HostRegexp: {subdomain:[a-z]+}.docker,test.morawskim.pl,{subdomain2:[a-z]+}.preview.morawskim.pl"
            networks:
              - default
              - traefik
            volumes:
              - "~/traefik2.yml:/etc/traefik/services.yml"
              - acme:/acme
              - /var/run/docker.sock:/var/run/docker.sock
            logging:
              driver: "json-file"
              options:
                max-file: "2"
                max-size: "20m"
            command:
              - --api.insecure=true
              - --providers.file.filename=/etc/traefik/services.yml
              - --providers.file.watch=true
              - --accesslog=true
              - --log.level=INFO
              - --entrypoints.web.address=:80
              - --entrypoints.internal.address=:81
              - --entrypoints.websecure.address=:443
              - --entrypoints.web.http.redirections.entryPoint.to=websecure
              - --entrypoints.web.http.redirections.entryPoint.scheme=https
              - --certificatesresolvers.myresolver.acme.email=marcin@morawskim.pl
              - --certificatesresolvers.myresolver.acme.storage=/acme/acme.json
              # used during the challenge
              - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
              - "--providers.docker=true"
              - "--providers.docker.exposedbydefault=false"
            extra_hosts:
              - "test.docker:192.168.111.88"
              - "tapo.docker:192.168.111.88"
      networks:
        traefik:
            external: true
      volumes:
        acme:
