- name: Add underscore if sufix is not empty
  set_fact:
    sufixWithOptionalUnderscore: "{{ '_' + sufix if sufix | length > 0 else '' }}"
- name: "debug variable sufixWithOptionalUnderscore"
  debug:
    var: sufixWithOptionalUnderscore
- name: "Create configuration file for traefikv2{{sufix}}"
  template:
    src: "templates/static-file-configuration{{sufixWithOptionalUnderscore}}.yml"
    dest: "~/traefik2{{sufixWithOptionalUnderscore}}.yml"
- name: Deploy traefikv2 via docker-compose
  docker_compose:
    project_name: traefikv2{{sufixWithOptionalUnderscore}}
    state: "present"
    definition:
      version: '3.3'
      services:
        traefik:
            image: traefik:v2.8
            restart: unless-stopped
            ports:
              - "{{port}}:8080"
              - "80:80"
              - "443:443"
            labels:
              traefik.enable: "true"
              traefik.port: "80"
              traefik.backend: "traefikv2{{sufix}}"
              traefik.docker.network: traefik
              traefik.frontend.rule: "{{regex}}"
            networks:
              - default
              - traefik
            volumes:
              - "~/traefik2{{sufixWithOptionalUnderscore}}.yml:/etc/traefik/services.yml"
              - acme:/acme
              - /var/run/docker.sock:/var/run/docker.sock
            logging:
              driver: "json-file"
              options:
                max-file: "2"
                max-size: "20m"
            command:
              - --api.insecure=true
              - --providers.file.filename=/etc/traefik/services.yml
              - --providers.file.watch=true
              - --accesslog=true
              - --log.level=INFO
              - --entrypoints.web.address=:80
              - --entrypoints.websecure.address=:443
              - --certificatesresolvers.myresolver.acme.email=marcin@morawskim.pl
              - --certificatesresolvers.myresolver.acme.storage=/acme/acme.json
              # used during the challenge
              - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
              - "--providers.docker=true"
              - "--providers.docker.exposedbydefault=false"
            extra_hosts:
              - "test.docker:192.168.111.88"
              - "tapo.docker:192.168.111.88"
      networks:
        traefik:
            external: true
      volumes:
        acme:
