- name: Deploy nextcloud via docker-compose
  docker_compose:
    project_name: nextcloud
    definition:
      version: '2.4'
      services:
        mysql:
          image: mysql:5.7
          restart: unless-stopped
          environment:
            - MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
            - MYSQL_USER={{NEXTCLOUD_DB_USER}}
            - MYSQL_PASSWORD={{NEXTCLOUD_DB_PASS}}
            - MYSQL_DATABASE={{NEXTCLOUD_DB_NAME}}
          command: --sort_buffer_size=2M
          volumes:
            - db:/var/lib/mysql
          logging:
            driver: "json-file"
            options:
              max-file: "2"
              max-size: "20m"
          mem_limit: 380M
        app:
          image: nextcloud
          restart: unless-stopped
          links:
            - mysql
          volumes:
            - nextcloud:/var/www/html
          environment:
            - MYSQL_PASSWORD={{NEXTCLOUD_DB_PASS}}
            - MYSQL_DATABASE={{NEXTCLOUD_DB_NAME}}
            - MYSQL_USER={{NEXTCLOUD_DB_USER}}
            - MYSQL_HOST=mysql
            - OVERWRITEPROTOCOL=https
          labels:
            traefik.enable: "true"
            traefik.port: "80"
            traefik.backend: "nextcloud"
            traefik.docker.network: traefik
            traefik.frontend.rule: "Host: nextcloud{{ APP_DOMAIN_SUFFIX }}"
          networks:
            - default
            - traefik
          logging:
            driver: "json-file"
            options:
              max-file: "2"
              max-size: "20m"
      volumes:
        db:
        nextcloud:
      networks:
        traefik:
            external: true
