apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  strategy: {}
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: httpbin
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 200m
            memory: 64Mi
        ports:
        - containerPort: 80
status: {}
