---
- hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Install required packages CLI
      package:
        name:
          - jq
          - tmux
          - fzf
          - nodejs
          - npm
          - pipx
          - vim
          - whois
          - ipcalc
          - bcal
          - colordiff
          - silversearcher-ag
        state: present
    - name: Install delta
      apt:
        deb: https://github.com/dandavison/delta/releases/download/0.12.1/git-delta_0.12.1_amd64.deb
    - name: Install required packages GUI
      package:
        name:
          - ghex
          - peek
          - libreoffice-l10n-pl
          - xclip
        state: present
    - name: Install snap packages
      snap:
        name:
          - ksnip
          - lsd
          - spotify
        state: present
    - name: Install snap classic packages
      snap:
        name:
          - helm
          - code
        classic: yes 
        state: present  
