---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: noip
spec:
  encryptedData:
    .env: AgAi3gnrxWiAH3sgLcbDM/Cwk3TkVngaQkteSNk0+c/+imdwIlzB6HQcGlBF3g0/LNiUXOS775pGh/rWKCGF2pIq65bLDdn4sw7gLuzTNSQpH3gDsiaR0Uj49sGe/GhYDG8WeZFPZSrm3xTaW6/seBe3q+S5L0Pvb/Gn+mYAHXCFg5d8CymzinyAmR/L/H7PhSGk4J/45esFXai7gQ6FBhZlgexPNZsTG0wgIkezI0wz9WmzaZZRCSuPL3DEx/aK2r5IFYGyHtW9fOOyTN4zyONGoYHfsnGNQBUsByPPADu/ZQvmG2NpOc7zqxq5bwbuhRNtOuZPi04VTig9IEwVQ4RlG3h0MR7G7KpK6tre67/DTqCuJ4nD8EWvb52YQ3Ksnhz+42RI+L2US9NnZ19ANnd37EBeGMlifbVzPQU7LtYg35vxDOOdHow2n0hTGbV6Zi0BsDjFLcBGXERJyzbpXZ3ELbriBlwBs8MD52wpHQZZkuv2Of8F7l7v9Zvwqw8kOQxPvvnROHbxb+H9P1/hCAXFVn/QSrfpNmZ1tw4Majbe9sKM79gYgFmNuT/0nE5W3TTUXg5kslg/m1k1Z8qPgemgbdHSJGPZC38h//DZitAt1haMzPVdhLcytJ7/gYfeXGVV7JFeRCyalLDbpFK1V5vs90aMXupqRCoUudpLaXIU7CPDwWChW2YmzQrxwyJXGK4G84USqx/rWl+DVkAMsH5zYaSrHHyzIxjHFWchU0oCX2/ottuVxvkSOlZZn9jeMKOp1lcmOb2+T6/QY6o4rKwdQmBBKV3bDSvNf8HDLNwx8wa+ryjhoMHu8QG/g1fs3tg=
  template:
    metadata:
      name: noip
