# frozen_string_literal: true

source "https://rubygems.org"

#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'test-kitchen', '~> 2.5'
gem 'kitchen-ansible', '~> 0.52'
gem 'kitchen-vagrant', '~> 1.6.1'
gem 'serverspec', '~> 2.41'
