kind: Namespace
apiVersion: v1
metadata:
  name: vagrant
---
kind: Namespace
apiVersion: v1
metadata:
  name: prod
---
kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
kind: Namespace
apiVersion: v1
metadata:
  name: traefik
