namespace: monitoring

resources:
- k8s-metrics
- ./newrelicSealedSecret.yaml
- ./kubeStateMetricsIngress.yml
- ./mysqldExporterSealedSecret.yml
- ./prometheus
- ./alertmanagerSealedSecret.yml
- ../../base/traefik-middlewares
- ../../base/mysqld-exporter
- ../../base/cloudwatch_exporter
- ./cloudwatchExporterSealedSecret.yml
- ./grafanacloudSealedSecret.yml
- ../../base/opentelemetry-collector
- ./opentelemetryCollectorSealedSecret.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
