---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysqld-exporter
  namespace: monitoring
spec:
  encryptedData:
    .my.cnf: AgBnUXZ4NLMvC+k4ILhBHYR1GfW9jwa++L9+ZoJBggVbum9GpDzDWk7Zs+G+gwFWKXC3V+onAITAsC9zMhlgmAyUyfQJtlHEpKXxaNu6gKghyudA2ojLyoq22XxpajOF22oyj+fKjn7Ct+betEIIA3WqAn9K4sK3RtjAbdmBWzsDJ/y4qeK7KaPv7W2FIAQJ9/FKju6hPMo/Ej5VYfL/O1QSVtUiHQ5Vep3wXZ7vWB6JZ4BUyxIY5d+jPfDoUWcAwuKzTYSq5VtySkDphZ8jTBKT2+ZxlPa5joCZOl8QuCqoITMCYQv9sOdDSXDgI50usHCyKL2BmCJw81b5VQ8T9MM8IrA0iURRu2eqd6+3wFAHRErfUGqLSy9tGHxhTQxVkqp8MLfQqbVQukqnewVG3+V4OxGCQbksTqH+UybGT0d+WMVfEedxtzbuhar5rqex5OLuDwBdTsQU032YlUFD9E/G/lgf+HOOQFh34QZy/kP2PCa6WgvHnGuh+wibIZoegjo3rdMEhZ3IXuH6xPYjYVfnVVYX3n3wkNBPW6cm3XfmLQx4e5vfHLUTdFoZSAv0/+c1w8m1sZDVe7NHdhD8D/V7A8EWoT6PjcJ/NRJvKRRCyUQ+yS8jOauXrs0AS3sODZqnKhEdPCHcN/4Kc1ggqRoGhosEMNLKEHv/m8Zou2CtyPC2i46S80GnyV4ix3Rml2xZnwUUopkCFJA/fmeMg912mJxpF0ZJ9N5qo1D8qhcMVqXicyGyeTuRgKpmEyf2nQUROFAGsA0RmS25rL16pugvQlW6SQ1d4r+rbcJsdpjdas2xGLHkm0Jf25hAu9U+6HMwESvIsneXvKYGGox8w/93cEiPTMLfHpFTZECf6AnhSiZoK23WLwrpVe0UMoRfYmEPITRoWv6KlThY4+Peyxf+NQy5HD0m89v2D34kizS6GcMhY0A/yHDQmYUfTgy3G/GDsf/Ud43Gs9sS48y26EEG+pKO6l2eBd8qFyIhuHRE2eFkrIMGHi6Uktvf
  template:
    metadata:
      creationTimestamp: null
      name: mysqld-exporter
      namespace: monitoring
    type: Opaque