---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: newrelic
spec:
  encryptedData:
    LICENSE_KEY: AgBwqg8qF+RB6T51QJ9Wwf6YizAtkDNVDY6Rc9MMQJdX6H0C2toHi7LBuuyZbndFCGes9EG6y+NrgMzh1pVp28N/rm6BrrI/s6/RgtXXDl+QIOpf/UKkgDXmCpZA4K0NMNDbnWSriP6vQt+lbE7GnNqsnjViJINoDpFawrrQU0YPoinZRa/Hrop3qRZAhq+wHKoS8a24Zqee8V4NwD9hFXRN0WpUzqubK3O3R38donWMKtzg/jOwmQy6C+p7/9ZRi0dKqdmtej4/tOVAB+t41xcF4fzNiekOnPgmBVVxemMc98pdxbmLbXYtJlGJX132pHZqep76HbfNEwfziH0n4sjQ8aBpqRNKwCoQoTWNP0Ay94tZnKg0PyRA5Dn9qV9AuwdR2ib40NIffKM7OQpmT6V8sCBHnwizmaW33de/b0YAZwRUweHgX5lpi0HB6mvfht2dEnZyp5jn1KvvKUaAYJEOxTzcVNms/QpJjWH454gjHn20BeordJITwxQl1Vp4BCWC6eWNh7GESpDSH7CWsHYpAyPHbmDe0AL8abx57OidHDplT0jd/2gaDC3B6m/AGiVQj8mGSWxajnFPQthdVj7YvljN7i2TBg2B0T8Yu80z776l7/SB+GCuRgJdBXabj/K0xH299b/CnvexPw9AcWVvtX7Hom6lJcoKJOZV25Q0PYdJAqzJF5NZDYZT1jpwic/RRu7c0YTbUOZ5nT61uedNZeBCoe8ktHiJj5DhZPASvRIjMVw2Ep5n
  template:
    metadata:
      name: newrelic
