apiVersion: v1
data:
  otel-collector-confing.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      otlphttp/grafana_cloud:
        endpoint: ${env:GRAFANA_CLOUD_OTLP_ENDPOINT}
        auth:
          authenticator: basicauth/grafana_cloud

    extensions:
      basicauth/grafana_cloud:
        client_auth:
          username: ${env:GRAFANA_CLOUD_INSTANCE_ID}
          password: ${env:GRAFANA_CLOUD_TOKEN}

    processors:
      batch:

    service:
      extensions: [basicauth/grafana_cloud]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/grafana_cloud]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/grafana_cloud]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/grafana_cloud]
kind: ConfigMap
metadata:
  name: opentelemetry-collector
