apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: price-tracker-exporter
  name: price-tracker-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-tracker-exporter
  strategy: {}
  template:
    metadata:
      labels:
        app: price-tracker-exporter
    spec:
      containers:
      - image: ghcr.io/morawskim/price-tracker:v0.2.1
        name: price-tracker-exporter
        imagePullPolicy: Always
        env:
        - name: CONFIG_URL
          valueFrom:
            secretKeyRef:
              name: price-tracker
              key: CONFIG_URL
        args:
          - "--config"
          - $(CONFIG_URL)
        resources: {}
status: {}
