apiVersion: v1
kind: Service
metadata:
  name: price-tracker-exporter
spec:
  selector:
    app: price-tracker-exporter
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
