---
- hosts: docker
  become: true
  gather_facts: yes
  vars:
    username: ubuntu
  vars_files:
    - parameters/vars.yml
    - parameters/secrets.yml
  pre_tasks:
    - name: Set a hostname
      hostname:
        name: "{{ vagrant_hostname | default('vm-docker') }}"
  roles:
    - name: newrelic.newrelic-infra
      vars:
        nrinfragent_config:
          license_key: "{{ NEWRELIC_LICENSE_KEY }}"
      when: "(vagrant_hostname is not defined) or (vagrant_hostname|length == 0)"
  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install docker
      package:
        name:
          - docker.io
          - docker-compose
    - name: Start docker
      service: name=docker enabled=true state=started
    - name: Add docker to the user's groups
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
    - name: Install node-exporter
      package:
        name: prometheus-node-exporter
    - name: Configure node-exporter
      lineinfile:
        path: /etc/default/prometheus-node-exporter
        regexp: '^ARGS='
        line: ARGS=--collector.netdev.ignored-devices="veth.*|br-.*" --collector.netclass.ignored-devices="veth.*|br-.*"
      notify: Restart node_exporter
    - name: Start node-exporter
      service: name=prometheus-node-exporter enabled=true state=started
    - include_tasks: tasks/fluentbit/playbook.yml
    - include_tasks: tasks/traefik2/playbook.yml
  handlers:
    - name: Restart node_exporter
      service:
        name: prometheus-node-exporter
        state: restarted
