---
- hosts: docker
  become: true
  gather_facts: yes
  vars:
    username: ubuntu
  vars_files:
    - parameters/vars.yml
    - parameters/secrets.yml
  pre_tasks:
    - name: Set a hostname
      hostname:
        name: "{{ vagrant_hostname | default('vm-docker') }}"
  roles:
    - name: newrelic.newrelic-infra
      vars:
        nrinfragent_config:
          license_key: "{{ NEWRELIC_LICENSE_KEY }}"
      when: "(vagrant_hostname is not defined) or (vagrant_hostname|length == 0)"
  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install docker
      package:
        name:
          - docker.io
          - docker-compose
    - name: Start docker
      service: name=docker enabled=true state=started
    - name: Add docker to the user's groups
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
    - name: Add entry to a hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
         - "192.168.111.88 test.docker"
         - "192.168.111.88 tapo.docker"
    - include_tasks: tasks/traefik.yml
    - include_tasks: tasks/ots.yml
    - include_tasks: tasks/nextcloud.yml
    - include_tasks: tasks/ttrss/ttrss.yml
    - include_tasks: tasks/noip/playbook.yml
    - include_tasks: tasks/fluentbit/playbook.yml
    - include_tasks: tasks/webpage2kindle.yml
    - include_tasks: tasks/prometheus/playbook.yml
    - include_tasks: tasks/backup.yml
    - include_tasks: tasks/traefik2/playbook.yml
      vars:
        sufix: ""
        port: 8889
        regex: "HostRegexp: {subdomain:[a-z]+}.docker,test.morawskim.pl,{subdomain2:[a-z]+}.preview.morawskim.pl"
    - include_tasks: tasks/gitlab-ci-pipelines-exporter/playbook.yml
    - include_tasks: tasks/up-to-date-exporter/playbook.yml
    - include_tasks: tasks/maddy/playbook.yml
    - include_tasks: tasks/jsonplaceholder.yml
    - include_tasks: tasks/ddns-updater/playbook.yml
