- name: Create env file for noip
  no_log: true
  template:
    src: templates/env.j2
    dest: "~/noip.env"
- name: Deploy noip via docker-compose
  docker_compose:
    project_name: noip
    remove_orphans: true
    definition:
      version: '3.3'
      services:
        app:
          image: ghcr.io/morawskim/noip-client-go:latest
          restart: unless-stopped
          command: "daemon"
          logging:
            driver: "json-file"
            options:
              max-size: "20m"
              max-file: "2"
          volumes:
            - ~/noip.env:/.env:ro
